### ISSUE TITLE
Link in README is broken

### ISSUE THREAD

**Issue by lemtronix** [arobenko/embxx#1]
Thanks for the awesome library, this will definitely come in handy!

I tried the link in the README file and it looks like it's no longer active (https://dl.dropboxusercontent.com/u/46999418/embxx/index.html).  Could you please update it?

Thanks again!
Mike

**Comment by arobenko** [comment]
Hi Mike,
I've tried this link from multiple computers/locations and it does work for me. Can you please check again? Maybe at the time you were trying the "Dropbox" service was malfunctioning or maybe you are behind a firewall that prevents you from connecting.

If it still doesn't work for you, can you please tell me whether it is the link itself doesn't open for you or a specific page when you try to navigate the documentation?

Regards,
Alex

**Comment by lemtronix** [comment]
You're correct, dropbox is blocked by my organization.  That link works from home.  Sorry for the inconvenience!
