### ISSUE TITLE
Unable to use StaticFunction without `operator delete`

### ISSUE THREAD

**Issue by trygvis** [arobenko/embxx#12]
With code similar to this:

    class i2c_slave {
        typedef embxx::util::StaticFunction<void(uint8_t *)> rx_complete_t;
        rx_complete_t rx_complete;
    }

I'm getting this error message:

    In function `embxx::util::StaticFunction<void (unsigned char*), 12u>::InvokerBound<display_ctrl_i2c::display_ctrl_i2c()::{lambda(unsigned char*)#2}>::~InvokerBound()':
    ../thirdparty/embxx/embxx/util/StaticFunction.h:353: undefined reference to `operator delete(void*, unsigned int)'

which was kinda surprising given the name of the class. Am I using the class in a bad way or what am I missing?

**Comment by arobenko** [comment]
Hi!
I'd like to refer you to the [Abstract Classes](https://arobenko.gitbooks.io/bare_metal_cpp/content/compiler_output/abstract_classes.html) chapter in my [Practical Guide to Bare Metal C++](https://www.gitbook.com/book/arobenko/bare_metal_cpp/details) e-book. 
You are probably using g++ as your compiler, which generates two destruction functions for classes with destructors declared as "virtual". One of them uses operator delete. I think it would be safe to stub the missing "operator delete()" function with empty body or some kind of assertion to make sure it is not called.

**Comment by trygvis** [comment]
Ok, adding the function fixed it. Thanks!
