### ISSUE TITLE
Moving the documentation

### ISSUE THREAD

**Issue by meuns** [arobenko/embxx#13]
Hello,

Dropbox suffers from "security issues" and various IT team just block it.

Could you move the documentation somewhere else ?

Best regards

**Comment by arobenko** [comment]
Hi there,
I've uploaded the documentation to the [release artifacts](https://github.com/arobenko/embxx/releases) as well.
Please let me know if there is any problem grabbing it from there.

**Comment by meuns** [comment]
It is fine for me ! Thank you
