### ISSUE TITLE
CompilerOptionsFuncs.cmake - Unix conditions

### ISSUE THREAD

**Issue by 0xc0170** [arobenko/embxx#2]
Why many macros in the CompilerOptionsFuncs cmake contain condition if (UNIX) ? Is there any intention?

An example:
```
macro (embxx_disable_exceptions)
    if (UNIX)
        embxx_add_cxx_flags("-fno-exceptions -fno-unwind-tables")
    endif ()
endmacro ()
```

I would like to remove that UNIX, because I don't think those flags contain anything specific for UNIX. I'll send PR shortly removing it from there

**Comment by arobenko** [comment]
See response in #4

**Comment by arobenko** [comment]
Merged to "develop" branch.
