### ISSUE TITLE
GCC 5.x support?

### ISSUE THREAD

**Issue by 0xc0170** [arobenko/embxx#5]
I am currently using gcc 5.x which caused some breakage in the c++11 support (reference https://gcc.gnu.org/gcc-5/porting_to.html). This affects this code base, I found few issues so far, therefore I ask before I do any bug fixing in this area.

A question -  move to gcc 5, or stay within gcc 4 ? The decision shall be documented in the readme

**Comment by arobenko** [comment]
I'm using Ubuntu Linux LTS as my primary development environment. The next LTS release is at the end of April this year, which will contain gcc 5. I plan to migrate to gcc 5 then, which will happen around May this year.

**Comment by 0xc0170** [comment]
OK, you would not mind if someone resolves this via a pull request fixing all breakage. We could do it it non-breaking way probably.

I switched yesterday back to v4.8 ,I'll stay within 4.x for now.

**Comment by arobenko** [comment]
You are welcome to resolve any Windows problems, I'll merge them. I don't really have an access to Windows development environment at home, only at work. However, I don't want to work on my own projects using my employer's equipment.

Please also note, that I'm not actively developing this library. It was my hobby project to get to know bare metal C++ better. I'm busy with other stuff at this moment, so don't expect any new features in the near future, unless you want to continue development yourself.

**Comment by arobenko** [comment]
I've just migrated to Ubuntu 16.04, which provides gcc v5.4.0 and haven't experienced any problems with the existing code base. Is there still any problem with your version of gcc?
